language: node_js
node_js:
    - "lts/*"

cache:
    directories:
        - node_modules

install:
    - npm install

script:
    - npm run validate

after_success:
    - npm run coverage

branches:
    only:
        - master
